name: unsigned-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name:  iOS Build (experimental/unsigned)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
        working-directory: app/

      - run: pod repo update
        working-directory: app/ios

      - run: flutter build ios --release --no-codesign --no-tree-shake-icons
        working-directory: app/

      - run: mkdir Payload
        working-directory: app/build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: app/build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: app/build/ios/iphoneos

      - name: Upload binaries as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios-binary
          path: app/build/ios/iphoneos/FlutterIpaExport.ipa
